export enum EIconNames {
  MANUAL_CONTROL = "control_manual",
  IN_OUT = "ingresos_salidas",
  PARKING_PAYMENT = "cobro_de_estacionamiento",
  CLOSURES = "cierres",
  CUSTOMERS = "clientes",
  PAYMENTS = "pagos",
  MONTHLY_PAYMENTS = "mensualidades",
  DASHBOARD = "dashboard",
  BLACKLIST = "lista_negra",
  WHITELIST = "lista_blanca",
  MASTERKEYS = "llaves_maestras",
  USERS = "usuarios",
  ROLES = "roles",
}